name: Release Automation
permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install --upgrade setuptools wheel
      - name: Generate release tag
        id: versioning
        run: |
          VERSION=$(date +'%Y.%m.%d')
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          generate_release_notes: true